### PR TITLE
PX 873 docker image

### PR DESCRIPTION
**Pull request by paolo-rechia**
Very simple strategy for speeding up build process.

- PX-873 rebuild on docker hub

### CODE REVIEW

**Review by matthew-bernardo — CHANGES_REQUESTED** [review]
:question: This looks great content-wise, but it's kind of odd that there are commits from PX-974 in this PR. If it would be a hassle to fix this, we don't need to, but I wanted to bring it up anyway.
:wrench: Do we have a different account that we can push this to? It's kind of odd for one person's account (paoloebot7) to be used for a team project. DevOps probably has some account that would be more appropriate. If this is just a temporary measure so we can fix our build process in the short-term, I don't mind so much.

**Comment by matthew-bernardo** [comment]
I think my comment about PX-974 is no longer relevant.

**Comment by paolo-rechia** [comment]
@matthew-bernardo yes, I think the right way is using our container registry in AWS or, as you said, a DevOps account. I can ping them. In any case, I'm just glad to see that we can effectively speed up the build process with this approach.
Do you think we should postpone this for the time being or can we get it fixed in this sprint?

**Review by maxim-ebot7 — APPROVED** [review]
lgtm!

**Review by maxim-ebot7 — APPROVED** [review]

**Comment by paolo-rechia** [comment]
Double checking, made another test with the updated commits. Looks good from end:

https://github.com/ebot7/serverless_functions/pull/277/checks?check_run_id=1362882270

@matthew-bernardo

**Review by matthew-bernardo — APPROVED** [review]
:+1: Clear commit history, and a ReadMe - good stuff

**Comment by paolo-rechia** [comment]
This was opened to the wrong base (`master`). :facepalm:
We need to update the base branch in repo settings.
New PR here: https://github.com/ebot7/eb7-sls-helper/pull/16

**Pull request closed without merging**
